app_crudl/urls.py
from django.urls import path

from app_login.views import Home
from .views import ABMPeriodos, ABMProcesos, ABMTareas, AgendaView, AgregarPeriodos, AgregarProcesos, EditarProcesos, EliminarProcesos, AgregarTareas, EditarAgenda, EditarPeriodos, EliminarAgenda, EliminarPeriodos, Tareasporperiodos, EliminarProcesos, EditarTareas, EliminarTareas, TareasxProcesoView
from django.contrib.auth import views as auth_views
from app_login.views import Home

app_name="app_crudl"
#app_name="abmprocesos"
#app_name="abmptareas"
#app_name="agenda"

urlpatterns = [  
# PERIODOS               
    path('abmperiodos/',ABMPeriodos.as_view(), name='abmperiodos' ),    
    path('agregarperiodos/',AgregarPeriodos.as_view(), name='agregarperiodos' ),        
    path('editarperiodos/<int:pk>',EditarPeriodos.as_view(), name='editarperiodos' ),            
    path('eliminarperiodos/<int:pk>',EliminarPeriodos.as_view(), name='eliminarperiodos' ),   
# PROCESOS                 
    path('abmprocesos/',ABMProcesos.as_view(), name='abmprocesos' ),      
    path('agregarprocesos/',AgregarProcesos.as_view(), name='agregarprocesos' ),
    path('editarprocesos/<int:pk>', EditarProcesos.as_view(), name='editarprocesos'),
    path('eliminarprocesos/<int:pk>', EliminarProcesos.as_view(), name='eliminarprocesos'),     
# TAREAS    
    path('abmtareas/',ABMTareas.as_view(), name='abmtareas' ),  
    path('agregartareas/',AgregarTareas.as_view(), name='agregartareas' ), 
    path('editartareas/<int:pk>', EditarTareas.as_view(), name='editartareas'),
    path('eliminartareas/<int:pk>', EliminarTareas.as_view(), name='eliminartareas'),
    path('tareasxproceso/',TareasxProcesoView.as_view(), name='tareasxproceso' ),      
    
# TAREA POR PERIODOS
    path('tareaporperiodos/',Tareasporperiodos.as_view(), name='tareaporperiodos' ),            
# AGENDA    
    path('agenda/',AgendaView.as_view(), name='agendaview' ),       
    path('editaragenda/<int:pk>',EditarAgenda.as_view(), name='editaragenda' ), 
    path('eliminaragenda/<int:pk>',EliminarAgenda.as_view(), name='eliminaragenda' ),          
#    path('', Home.as_view(), name="index")  
    ]

app_login/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from app_login.views import Home

app_name="login"

urlpatterns = [
   
    path('login/',auth_views.LoginView.as_view(template_name='login.html'), name='login' ),    
    path('logout/',auth_views.LogoutView.as_view(template_name='login.html'),name='logout' ),  
    path('', Home.as_view(), name='index')    
    ]

proyecto_seguimiento_mefi/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path, include

urlpatterns = [
    path('', include('app_login.urls', namespace='login')),
    path('', include('app_crudl.urls', namespace='app_crudl')),    
    path('admin/', admin.site.urls),
]

templates/abm_periodos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ABM PERIODOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Listado de Periodos</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>Nombre</th>
            <th>Acciones</th>            
          </tr>
        </thead>
        <tbody>
          {% for i in obj %}
          <tr>
            <td>{{i.id}}</td>
            <td>{{i.nombre}}</td>
            <td>
                <a href="{% url 'app_crudl:editarperiodos' i.id %}" class="btn btn-success"><i class="far fa-edit"></i> Editar</a>
                <a href="{% url 'app_crudl:eliminarperiodos' i.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i> Eliminar</a>

<!--                <a href="#" class="btn btn-primary">Editar</a>
                <a href="#" class="btn btn-danger">Eliminar</a>-->                
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/abm_procesos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ABM PROCESOS</h1>
    </div>    
  </div>
 
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="container">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Listado de Procesos</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>Período</th>
            <th>Descripción</th>
            <th>Acciones</th>            
          </tr>
        </thead>
        <tbody>
          {% for i in obj %}
          <tr>
            <td>{{i.id}}</td>
            <td>{{i.nombre}}</td>
            <td>{{i.descripcion}}</td>
            <td>
 
                <a href="{% url 'app_crudl:editarprocesos' i.id %}" class="btn btn-success"><i class="far fa-edit"></i> Editar</a>
                <a href="{% url 'app_crudl:eliminarprocesos' i.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i> Eliminar</a>

<!--                <a href="#" class="btn btn-primary">Editar</a>
                <a href="#" class="btn btn-danger">Eliminar</a>-->                
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/abm_tareas.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ABM TAREAS</h1>
    </div>    
  </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="container">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Listado de Tareas</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Proceso</th>
            <th>Activa ?</th>
            <th>Priodidad</th> 
            <th>Acciones</th>           
          </tr>
        </thead>
        <tbody>
          {% for i in obj %}
          <tr>
            <td>{{i.id}}</td>

            <td>{{i.nombre}}</td>
            {% if i.descripcion  %}
              <td>{{i.descripcion}}</td>
            {% else %} 
              <td>Sin descripición.</td>
            {% endif %}
            <td>{{i.id_proceso }}</td>
            <td><span class="badge bg-orange">{{i.activa|yesno:"SI,NO" }}</span></td>
            <td>{{i.prioridad}}</td>
            <td>
 
                <a href="{% url 'app_crudl:editartareas' i.id %}" class="btn btn-success"><i class="far fa-edit"></i> Editar</a>
                <a href="{% url 'app_crudl:eliminartareas' i.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i> Eliminar</a>

<!--                <a href="#" class="btn btn-primary">Editar</a>
                <a href="#" class="btn btn-danger">Eliminar</a>-->                
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/agregar_procesos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>AGREGAR PROCESOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Agregar Procesos</h3>
    </div>
    <!-- /.card-header -->
    <form role="form" method="post"> {% csrf_token %}
      {{form.as_p}}
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/agregar_tareas.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>AGREGAR TAREAS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Agregar Tareas</h3>
    </div>
    <!-- /.card-header -->
    <form role="form" method="post"> {% csrf_token %}
      {{form.as_p}}
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Seguimiento de Tareas - Sueldos Informatica</title>

  <link rel="shortcut icon" href="/static/img/python_18894.ico">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="https://adminlte.io/themes/v3/dist/css/adminlte.min.css">
  
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>  

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">

  
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <div class="info">
              <a class="d-block">Usuario:  {{user.username}}</a>
              <div class="pull-right">
                <td>
                  <a href="{% url 'login:logout' %}"><button type="button" class="btn btn-block btn-primary">Cerrar Sesion</button></a>
                </td>              
              </div>
            </div>
          </div>          
        </div>
  

        <!-- Sidebar Menu -->
        {% block menu %}        
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->               
            <li class="nav-item">
                <li><a href="{% url 'app_crudl:tareasxproceso'%}"><i class="fa fa-home nav-header text-info"></i>INICIO</a></li></a>
            <li class="nav-header"></li>
            <li class="nav-header">MENU PRINCIPAL</li>            
            <li class="nav-item">
              <a href="#" class="nav-link active">
                <i class="nav-icon fas  fa-database"></i>
                <p>
                  Procesos
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview" style="display: none;">
                <li class="nav-item">
                  <a href="{% url 'app_crudl:abmprocesos'%}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Listado de Procesos</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'app_crudl:agregarprocesos'%}" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Agregar Procesos</p>
                  </a>
              </ul>
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="nav-icon fas  fa-users"></i>
                  <p>
                    Tareas
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                  <li class="nav-item">
                    <a href="{% url 'app_crudl:abmtareas'%}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Listado de Tareas</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'app_crudl:agregartareas'%}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Agregar Tareas</p>
                    </a>
                </li></ul>
                
              </li>              
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="nav-icon fas  fa-suitcase"></i>
                  <p>
                    Periodos
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                  <li class="nav-item">
                    <a href="{% url 'app_crudl:abmperiodos'%}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Listado de Periodos</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'app_crudl:agregarperiodos'%}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Agregar Periodos</p>
                    </a>
                </li></ul>                
              </li>               
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="nav-icon fas  fa-tasks"></i>
                  <p>
                    Agenda
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                  <li class="nav-item">
                    <a href="{% url 'app_crudl:agendaview'%}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Agenda</p>
                    </a>
                  </li>
                </ul>   
                               
                <BR></BR>             
                <li class="nav-header">ACCIONES</li>
                <li class="nav-item">
                  <a href="{% url 'app_crudl:tareaporperiodos'%}" class="nav-link">
                    <i class="nav-icon far fa-circle text-danger"></i>
                    <p class="text">Tareas por Periodo</p>
                  </a>
                </li> 
                              
              </li>               
            </li>
          </ul>
        </nav>
        {% endblock %}        
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
  
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">       
        <div class="container-fluid">
          {% block titulo %}           
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Blank Page</h1>
            </div>
          </div>
          {% endblock %} 
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      {% block contenido %}      
      <section class="content">
  
        <!-- Default box -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Title</h3>
  
            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <div class="card-body">
            Start creating your amazing application!
          </div>
          <!-- /.card-body -->
          <div class="card-footer">
            Footer
          </div>
          <!-- /.card-footer-->
        </div>
        <!-- /.card -->
  
      </section>
      {% endblock %}
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
  
    <footer class="main-footer">
      <strong>Copyright &copy; 2021 Ministerio de Economia, Finanzas e Infraestructura</a>.</strong>
    </footer>
  
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->
  
  <!-- jQuery -->
  <script src="https://adminlte.io/themes/v3/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="https://adminlte.io/themes/v3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="https://adminlte.io/themes/v3/dist/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="https://adminlte.io/themes/v3/dist/js/demo.js"></script>
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>

  </body>
  
</html>

templates/editar_agenda.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>EDITAR AGENDA</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Editar Periodos</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      {{form.as_p}}          
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-success btn-sm">Editar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/editar_periodos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>EDITAR PERIODOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Editar Periodos</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      {{form.as_p}}          
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-success btn-sm">Editar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/editar_procesos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>EDITAR PROCESOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Editar Procesos</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      {{form.as_p}}          
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-success btn-sm">Editar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/eliminar_agenda.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ELIMINAR PERIODOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Eliminar Periodos</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>ID PERIODO</th> 
            <th>ID TAREA</th> 
            <th>ID FINALIZADA</th>         
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{obj.id}}</td>
            <td>{{obj.id_periodo }}</td>
            <td>{{obj.id_tarea }}</td>
            <td>{{i.finalizada|yesno:"SI,NO" }}</td>
          </tr>          
        </tbody>       
      </table>     
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-danger btn-sm">Eliminar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/eliminar_procesos.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ELIMINAR PROCESOS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Eliminar Procesos</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>Nombre</th>         
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{obj.id}}</td>
            <td>{{obj.nombre}}</td>
          </tr>          
        </tbody>       
      </table>     
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-danger btn-sm">Eliminar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/eliminar_tareas.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>ELIMINAR TAREAS</h1>
    </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}    
<section class="col-md-6">
  <div class="card" >
    <div class="card-header">
      <h3 class="card-title">Eliminar Tareas</h3>
    </div>
    <!-- /.card-header -->
    <form method="POST" > {% csrf_token%}
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 10px">ID</th>
            <th>Nombre</th>         
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{obj.id}}</td>
            <td>{{obj.nombre}}</td>
          </tr>          
        </tbody>       
      </table>     
      <div class="box-footer">
        <button type="submit" class="btn btn-block btn-danger btn-sm">Eliminar</button>
      </div>       
     </form>
    <!-- /.card-body -->
  </div>

</section>
<!-- /.content -->
{% endblock %}    

templates/home.html
{%extends 'base.html'%}

{% block titulo %}
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>INICIO</h1>
    </div>   
  </div>
</div><!-- /.container-fluid -->
{% endblock %}

{% block contenido %}
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed bg-blue" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="tr" aria-controls="panelsStayOpen-collapseTwo">
        1 - COBOL PRELIQUIDACION
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">         
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="width: 10px">ID</th>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Proceso</th>
              <th>Activa</th>           
            </tr>
          </thead>
          <tbody>           
            {% for i in obj %}            
            <tr>
              {% if i.id == 3 %}  
                <td>{{i.id}}</td>
                <td>{{i.nombre}}</td>
                {% if i.descripcion  %}
                  <td>{{i.descripcion}}</td>
                {% else %} 
                  <td>Sin descripición.</td>
                {% endif %}
                <td>{{i.id_proceso}}</td>
                <td><span class="badge bg-orange">{{i.activa|yesno:"SI,NO" }}</span></td>  
              {% endif %}
            </tr>
            {% endfor %}           
          </tbody>
        </table>              
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed bg-blue" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        2 - COBOL LIQUIDACION
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-heading4">
      <button class="accordion-button collapsed bg-blue" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse4" aria-expanded="false" aria-controls="panelsStayOpen-collapse4">
        3 - COBOL POSTLIQUIDACION
      </button>
    </h2>
    <div id="panelsStayOpen-collapse4" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading4">
      <div class="accordion-body">
      </div>
    </div>
  </div>  
</div>
{% endblock%}